import { EquipantType, LubricantType } from './types';

export const EQUIPMENT_DATABASE: EquipmentData[] = [
  {
    id: '301-C-01',
    tagNo: '301-C-01',
    description: 'Gas Compressor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (301-TK-51)'
  },
  {
    id: '302-C-01',
    tagNo: '302-C-01',
    description: 'Gas Compressor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (302-TK-51)'
  },
  {
    id: '303-C-01',
    tagNo: '303-C-01',
    description: 'Gas Compressor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (303-TK-51)'
  },
  {
    id: '751-C-01',
    tagNo: '751-C-01',
    description: 'Gas Compressor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (751-TK-51)'
  },
  {
    id: '752-C-01',
    tagNo: '752-C-01',
    description: 'Gas Compressor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (752-TK-51)'
  },
  {
    id: '753-C-01',
    tagNo: '753-C-01',
    description: 'Gas Compressor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (753-TK-51)'
  },
  {
    id: '754-C-01',
    tagNo: '754-C-01',
    description: 'Gas Compressor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (754-TK-51)'
  },
  {
    id: '301-CM-01',
    tagNo: '301-CM-01',
    description: 'Gs Compressor Main Drive Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (301-TK-51)'
  },
  {
    id: '302-CM-01',
    tagNo: '302-CM-01',
    description: 'Gs Compressor Main Drive Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (302-TK-51)'
  },
  {
    id: '303-CM-01',
    tagNo: '303-CM-01',
    description: 'Gs Compressor Main Drive Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (303-TK-51)'
  },
  {
    id: '751-CM-01',
    tagNo: '751-CM-01',
    description: 'Gs Compressor Main Drive Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (751-TK-51)'
  },
  {
    id: '752-CM-01',
    tagNo: '752-CM-01',
    description: 'Gs Compressor Main Drive Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (752-TK-51)'
  },
  {
    id: '753-CM-01',
    tagNo: '753-CM-01',
    description: 'Gs Compressor Main Drive Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (753-TK-51)'
  },
  {
    id: '754-CM-01',
    tagNo: '754-CM-01',
    description: 'Gs Compressor Main Drive Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (754-TK-51)'
  },
  {
    id: '301-CG-01',
    tagNo: '301-CG-01',
    description: 'Gear Box',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (301-TK-51)'
  },
  {
    id: '302-CG-01',
    tagNo: '302-CG-01',
    description: 'Gear Box',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (302-TK-51)'
  },
  {
    id: '303-CG-01',
    tagNo: '303-CG-01',
    description: 'Gear Box',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (303-TK-51)'
  },
  {
    id: '751-CG-01',
    tagNo: '751-CG-01',
    description: 'Gear Box',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (751-TK-51)'
  },
  {
    id: '752-CG-01',
    tagNo: '752-CG-01',
    description: 'Gear Box',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (752-TK-51)'
  },
  {
    id: '753-CG-01',
    tagNo: '753-CG-01',
    description: 'Gear Box',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (753-TK-51)'
  },
  {
    id: '754-CG-01',
    tagNo: '754-CG-01',
    description: 'Gear Box',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (754-TK-51)'
  },
  {
    id: '301-P-51A',
    tagNo: '301-P-51A',
    description: 'Main Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (301-TK-51)'
  },
  {
    id: '302-P-51A',
    tagNo: '302-P-51A',
    description: 'Main Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (302-TK-51)'
  },
  {
    id: '303-P-51A',
    tagNo: '303-P-51A',
    description: 'Main Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (303-TK-51)'
  },
  {
    id: '751-P-51A',
    tagNo: '751-P-51A',
    description: 'Main Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (751-TK-51)'
  },
  {
    id: '752-P-51A',
    tagNo: '752-P-51A',
    description: 'Main Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (752-TK-51)'
  },
  {
    id: '753-P-51A',
    tagNo: '753-P-51A',
    description: 'Main Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (753-TK-51)'
  },
  {
    id: '754-P-51A',
    tagNo: '754-P-51A',
    description: 'Main Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (754-TK-51)'
  },
  {
    id: '301-P-51B',
    tagNo: '301-P-51B',
    description: 'Auxiliary Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (301-TK-51)'
  },
  {
    id: '302-P-51B',
    tagNo: '302-P-51B',
    description: 'Auxiliary Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (302-TK-51)'
  },
  {
    id: '303-P-51B',
    tagNo: '303-P-51B',
    description: 'Auxiliary Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (303-TK-51)'
  },
  {
    id: '751-P-51B',
    tagNo: '751-P-51B',
    description: 'Auxiliary Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (751-TK-51)'
  },
  {
    id: '752-P-51B',
    tagNo: '752-P-51B',
    description: 'Auxiliary Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (752-TK-51)'
  },
  {
    id: '753-P-51B',
    tagNo: '753-P-51B',
    description: 'Auxiliary Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (753-TK-51)'
  },
  {
    id: '754-P-51B',
    tagNo: '754-P-51B',
    description: 'Auxiliary Lube Oil Pump',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Quantity included in respective skid mounted Lube Oil Tank (754-TK-51)'
  },
  {
    id: '301-TK-51',
    tagNo: '301-TK-51',
    description: 'Lube Oil Tank',
    part: 'Lube Oil Tank',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '7103 L',
    topUpQty: '59 L',
    topUpInterval: '720 hrs',
    replacementInterval: 'Based on oil analysis',
    brands: { bp: 'CASTROL PERFECTO XEP 46', shell: 'TELLUS OIL 46', total: 'PRESLIA 46', naftal: 'TORBA 46' },
    remarks: '1. Oil shall be Turbine Quality Mineral Oil. 2. During start up, check monthly until 6 months. After 6 months, oil analysis every 6 months. 3. Yearly consumption 710 litres.'
  },
  {
    id: '302-TK-51',
    tagNo: '302-TK-51',
    description: 'Lube Oil Tank',
    part: 'Lube Oil Tank',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '7103 L',
    topUpQty: '59 L',
    topUpInterval: '720 hrs',
    replacementInterval: 'Based on oil analysis',
    brands: { bp: 'CASTROL PERFECTO XEP 46', shell: 'TELLUS OIL 46', total: 'PRESLIA 46', naftal: 'TORBA 46' },
    remarks: '1. Oil shall be Turbine Quality Mineral Oil. 2. During start up, check monthly until 6 months. After 6 months, oil analysis every 6 months. 3. Yearly consumption 710 litres.'
  },
  {
    id: '303-TK-51',
    tagNo: '303-TK-51',
    description: 'Lube Oil Tank',
    part: 'Lube Oil Tank',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '7103 L',
    topUpQty: '59 L',
    topUpInterval: '720 hrs',
    replacementInterval: 'Based on oil analysis',
    brands: { bp: 'CASTROL PERFECTO XEP 46', shell: 'TELLUS OIL 46', total: 'PRESLIA 46', naftal: 'TORBA 46' },
    remarks: '1. Oil shall be Turbine Quality Mineral Oil. 2. During start up, check monthly until 6 months. After 6 months, oil analysis every 6 months. 3. Yearly consumption 710 litres.'
  },
  {
    id: '751-TK-51',
    tagNo: '751-TK-51',
    description: 'Lube Oil Tank',
    part: 'Lube Oil Tank',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '7103 L',
    topUpQty: '59 L',
    topUpInterval: '720 hrs',
    replacementInterval: 'Based on oil analysis',
    brands: { bp: 'CASTROL PERFECTO XEP 46', shell: 'TELLUS OIL 46', total: 'PRESLIA 46', naftal: 'TORBA 46' },
    remarks: '1. Oil shall be Turbine Quality Mineral Oil. 2. During start up, check monthly until 6 months. After 6 months, oil analysis every 6 months. 3. Yearly consumption 710 litres.'
  },
  {
    id: '752-TK-51',
    tagNo: '752-TK-51',
    description: 'Lube Oil Tank',
    part: 'Lube Oil Tank',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '7103 L',
    topUpQty: '59 L',
    topUpInterval: '720 hrs',
    replacementInterval: 'Based on oil analysis',
    brands: { bp: 'CASTROL PERFECTO XEP 46', shell: 'TELLUS OIL 46', total: 'PRESLIA 46', naftal: 'TORBA 46' },
    remarks: '1. Oil shall be Turbine Quality Mineral Oil. 2. During start up, check monthly until 6 months. After 6 months, oil analysis every 6 months. 3. Yearly consumption 710 litres.'
  },
  {
    id: '753-TK-51',
    tagNo: '753-TK-51',
    description: 'Lube Oil Tank',
    part: 'Lube Oil Tank',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '7103 L',
    topUpQty: '59 L',
    topUpInterval: '720 hrs',
    replacementInterval: 'Based on oil analysis',
    brands: { bp: 'CASTROL PERFECTO XEP 46', shell: 'TELLUS OIL 46', total: 'PRESLIA 46', naftal: 'TORBA 46' },
    remarks: '1. Oil shall be Turbine Quality Mineral Oil. 2. During start up, check monthly until 6 months. After 6 months, oil analysis every 6 months. 3. Yearly consumption 710 litres.'
  },
  {
    id: '754-TK-51',
    tagNo: '754-TK-51',
    description: 'Lube Oil Tank',
    part: 'Lube Oil Tank',
    package: 'JI2045-0-PFM101',
    type: LubricantType.OIL,
    grade: 'ISO VG 46',
    initialFill: '7103 L',
    topUpQty: '59 L',
    topUpInterval: '720 hrs',
    replacementInterval: 'Based on oil analysis',
    brands: { bp: 'CASTROL PERFECTO XEP 46', shell: 'TELLUS OIL 46', total: 'PRESLIA 46', naftal: 'TORBA 46' },
    remarks: '1. Oil shall be Turbine Quality Mineral Oil. 2. During start up, check monthly until 6 months. After 6 months, oil analysis every 6 months. 3. Yearly consumption 710 litres.'
  },
  {
    id: '301-PM-51A',
    tagNo: '301-PM-51A',
    description: 'Main Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '302-PM-51A',
    tagNo: '302-PM-51A',
    description: 'Main Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '303-PM-51A',
    tagNo: '303-PM-51A',
    description: 'Main Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '751-PM-51A',
    tagNo: '751-PM-51A',
    description: 'Main Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '752-PM-51A',
    tagNo: '752-PM-51A',
    description: 'Main Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '753-PM-51A',
    tagNo: '753-PM-51A',
    description: 'Main Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '754-PM-51A',
    tagNo: '754-PM-51A',
    description: 'Main Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '301-PM-51B',
    tagNo: '301-PM-51B',
    description: 'Auxiliary Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '302-PM-51B',
    tagNo: '302-PM-51B',
    description: 'Auxiliary Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '303-PM-51B',
    tagNo: '303-PM-51B',
    description: 'Auxiliary Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '751-PM-51B',
    tagNo: '751-PM-51B',
    description: 'Auxiliary Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '752-PM-51B',
    tagNo: '752-PM-51B',
    description: 'Auxiliary Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '753-PM-51B',
    tagNo: '753-PM-51B',
    description: 'Auxiliary Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '754-PM-51B',
    tagNo: '754-PM-51B',
    description: 'Auxiliary Lube Oil Pump Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '35 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '1475 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '301-EAF-51A',
    tagNo: '301-EAF-51A',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '301-EAF-51B',
    tagNo: '301-EAF-51B',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '301-EAF-51C',
    tagNo: '301-EAF-51C',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '302-EAF-51A',
    tagNo: '302-EAF-51A',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '302-EAF-51B',
    tagNo: '302-EAF-51B',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '302-EAF-51C',
    tagNo: '302-EAF-51C',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '303-EAF-51A',
    tagNo: '303-EAF-51A',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '303-EAF-51B',
    tagNo: '303-EAF-51B',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '303-EAF-51C',
    tagNo: '303-EAF-51C',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '751-EAF-51A',
    tagNo: '751-EAF-51A',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '751-EAF-51B',
    tagNo: '751-EAF-51B',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '751-EAF-51C',
    tagNo: '751-EAF-51C',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '752-EAF-51A',
    tagNo: '752-EAF-51A',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '752-EAF-51B',
    tagNo: '752-EAF-51B',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '752-EAF-51C',
    tagNo: '752-EAF-51C',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '753-EAF-51A',
    tagNo: '753-EAF-51A',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '753-EAF-51B',
    tagNo: '753-EAF-51B',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '753-EAF-51C',
    tagNo: '753-EAF-51C',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '754-EAF-51A',
    tagNo: '754-EAF-51A',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '754-EAF-51B',
    tagNo: '754-EAF-51B',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '754-EAF-51C',
    tagNo: '754-EAF-51C',
    description: 'Lube Oil Cooler Fan',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '140 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '3000 hrs',
    brands: { bp: 'Olista Longtime 3EP', shell: 'Alvania EP2 / Gadus S2 V220 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'AGIP GR MU EP2 / IP ATHESIA EP2' },
    remarks: 'Lithium Grease. Initial Fill at Factory. If stationary >30 days, re-lubricate before restart.'
  },
  {
    id: '301-EAM-51A',
    tagNo: '301-EAM-51A',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '301-EAM-51B',
    tagNo: '301-EAM-51B',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '301-EAM-51C',
    tagNo: '301-EAM-51C',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '302-EAM-51A',
    tagNo: '302-EAM-51A',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '302-EAM-51B',
    tagNo: '302-EAM-51B',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '302-EAM-51C',
    tagNo: '302-EAM-51C',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '303-EAM-51A',
    tagNo: '303-EAM-51A',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '303-EAM-51B',
    tagNo: '303-EAM-51B',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '303-EAM-51C',
    tagNo: '303-EAM-51C',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '751-EAM-51A',
    tagNo: '751-EAM-51A',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '751-EAM-51B',
    tagNo: '751-EAM-51B',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '751-EAM-51C',
    tagNo: '751-EAM-51C',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '752-EAM-51A',
    tagNo: '752-EAM-51A',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '752-EAM-51B',
    tagNo: '752-EAM-51B',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '752-EAM-51C',
    tagNo: '752-EAM-51C',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '753-EAM-51A',
    tagNo: '753-EAM-51A',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '753-EAM-51B',
    tagNo: '753-EAM-51B',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '753-EAM-51C',
    tagNo: '753-EAM-51C',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '754-EAM-51A',
    tagNo: '754-EAM-51A',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '754-EAM-51B',
    tagNo: '754-EAM-51B',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '754-EAM-51C',
    tagNo: '754-EAM-51C',
    description: 'Lube Oil Cooler Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '301-EAM-52A',
    tagNo: '301-EAM-52A',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '301-EAM-52B',
    tagNo: '301-EAM-52B',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '301-EAM-52C',
    tagNo: '301-EAM-52C',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '302-EAM-52A',
    tagNo: '302-EAM-52A',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '302-EAM-52B',
    tagNo: '302-EAM-52B',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '302-EAM-52C',
    tagNo: '302-EAM-52C',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '303-EAM-52A',
    tagNo: '303-EAM-52A',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '303-EAM-52B',
    tagNo: '303-EAM-52B',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '303-EAM-52C',
    tagNo: '303-EAM-52C',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '751-EAM-52A',
    tagNo: '751-EAM-52A',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '751-EAM-52B',
    tagNo: '751-EAM-52B',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '751-EAM-52C',
    tagNo: '751-EAM-52C',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '752-EAM-52A',
    tagNo: '752-EAM-52A',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '752-EAM-52B',
    tagNo: '752-EAM-52B',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '752-EAM-52C',
    tagNo: '752-EAM-52C',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '753-EAM-52A',
    tagNo: '753-EAM-52A',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '753-EAM-52B',
    tagNo: '753-EAM-52B',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '753-EAM-52C',
    tagNo: '753-EAM-52C',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '754-EAM-52A',
    tagNo: '754-EAM-52A',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '754-EAM-52B',
    tagNo: '754-EAM-52B',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '754-EAM-52C',
    tagNo: '754-EAM-52C',
    description: 'MV Motor Cooling Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: 'NLGI Grade 3',
    initialFill: '30 g',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '7550 hrs',
    brands: { shell: 'Gadus S5 V 100 2 / Unirex N2 or N3', mobil: 'Mobilith SHC 100', total: 'Multis Complex S2 A', other: 'Rhenus LKZ 2 / Klüber Kl³berplex BEM 41-132 / FAG Arcanol TEMP110 / Lubcon Turmogrease L 802 EP PLUS' },
    remarks: 'Lithium Grease. Initial Fill of Grease at Factory.'
  },
  {
    id: '301-VFM-51',
    tagNo: '301-VFM-51',
    description: 'Oil Mist Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '302-VFM-51',
    tagNo: '302-VFM-51',
    description: 'Oil Mist Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '303-VFM-51',
    tagNo: '303-VFM-51',
    description: 'Oil Mist Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '751-VFM-51',
    tagNo: '751-VFM-51',
    description: 'Oil Mist Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '752-VFM-51',
    tagNo: '752-VFM-51',
    description: 'Oil Mist Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '753-VFM-51',
    tagNo: '753-VFM-51',
    description: 'Oil Mist Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  },
  {
    id: '754-VFM-51',
    tagNo: '754-VFM-51',
    description: 'Oil Mist Fan Motor',
    part: 'Bearings',
    package: 'JI2045-0-PFM101',
    type: LubricantType.GREASE,
    grade: '-',
    initialFill: '-',
    topUpQty: '-',
    topUpInterval: '-',
    replacementInterval: '-',
    brands: {},
    remarks: 'Greased For Life'
  }
];
